Refactoring models
LT-Students/DigitalOffice-NewsService pull request #21
Opened 2021-04-06 22:22 UTC by KostinP

2021-04-07 19:34 UTC, djino97 requested changes

2021-04-07 19:34 UTC, djino97 commented on src/NewsService.Models.Dto/NewsService.Models.Dto.csproj
> +  </ItemGroup>
What is this?

2021-04-07 19:34 UTC, djino97 commented on src/NewsService.Data/Interfaces/INewsRepository.cs
>          /// <param name="findNewsParams">Params for serch.</param>
need fix

2021-04-07 19:46 UTC, BelehovEgor requested changes

2021-04-07 19:46 UTC, BelehovEgor commented on src/NewsService.Business/Interfaces/IFindNewsCommand.cs
> +        public List<NewsResponse> Execute(FindNewsFilter findNewsFilter);
delete public

2021-04-07 20:00 UTC, KostinP commented on src/NewsService.Models.Dto/NewsService.Models.Dto.csproj
> +  </ItemGroup>
Fixed.

2021-04-07 20:00 UTC, KostinP commented on src/NewsService.Data/Interfaces/INewsRepository.cs
>          /// <param name="findNewsParams">Params for serch.</param>
Fixed.

2021-04-07 20:01 UTC, KostinP commented on src/NewsService.Business/Interfaces/IFindNewsCommand.cs
> +        public List<NewsResponse> Execute(FindNewsFilter findNewsFilter);
Removed.

2021-04-08 04:52 UTC, BelehovEgor approved these changes

2021-04-08 07:46 UTC, borovHokage approved these changes

2021-04-08 08:57 UTC, TIove approved these changes

2021-04-08 10:02 UTC, djino97 approved these changes

2021-04-08 10:17 UTC, merged